### ISSUE TITLE
Searching for project objective

### ISSUE THREAD

**Issue by varsha-kankariya** [hirparikh/Team-Project-1#1]

**Comment by varsha-kankariya** [comment]
Hiral has suggested following topics:

1. Searching Algorihtm
2. Sorting Algorithm
3. devide and conquer
4. minimal spanning tree 


Please reply back with your suggestions or if you have more topics.We can add them to the list and discuss.

**Comment by TootyFrooty** [comment]
I'm totally down for:
    4. Minimal Spanning Tree

Or one of the following:
   1. Artificial Intelligence - we could probably build multi-level games where we let the player compete against computer on fastest recollection from face down cards, fastest to finish maze (trees/ network), fastest to solve Sudoku (for finale)
   2. Steiner Tree

**Comment by varsha-kankariya** [comment]
I am good with Minimal spanning tree and searching algorithms.

**Comment by varsha-kankariya** [comment]
I have narrowed down to one ...minimal spanning tree ...

**Comment by vikasmiyani** [comment]
I am down for Minimal spanning tree and searching algorithm

**Comment by hirparikh** [comment]
I narrowed four option suggested earlier by me to - Minimal Spanning Tree and Searching Algorithm

**Comment by TootyFrooty** [comment]
Let's finalize Minimal spanning tree as almost everyone is in agreement on that!

**Comment by varsha-kankariya** [comment]
I am also good with minimal spanning tree.

**Comment by varsha-kankariya** [comment]
@Darshit : Could you please confirm the CS unplugged activities you are interested in? If you are interested in discussing any other activities, we can do it on coming Saturday.

**Comment by hirparikh** [comment]
Project Objective has been finalized to Minimal Spanning Tree.
