### ISSUE TITLE
Submit Team Name

### ISSUE THREAD

**Issue by varsha-kankariya** [hirparikh/Team-Project-1#2]

**Comment by TootyFrooty** [comment]
If we're going with Trees/ AI, i feel the common goal or end result is "SPEED". So why don't we come up with names around that idea?

Maybe we could use - Bolt, Zippy

**Comment by varsha-kankariya** [comment]
I have few suggestions too as speed is going to be the main focus : Speedy Amigos, Speedster, Boosters...

**Comment by vikasmiyani** [comment]
i think Speedy Amigos and zippy would be better.

**Comment by hirparikh** [comment]
I suggest 'Brightbuds' or 'Zippy'

**Comment by varsha-kankariya** [comment]
BrightBuds it is...
