### ISSUE TITLE
Choose one of the XP values

### ISSUE THREAD

**Issue by varsha-kankariya** [hirparikh/Team-Project-1#3]

**Comment by vikasmiyani** [comment]
I will choose communication as XP value

**Comment by TootyFrooty** [comment]
For my XP, i'll choose "See the whole"

**Comment by dthesiya** [comment]
I will work on 'Build Integrity In'

**Comment by varsha-kankariya** [comment]
I will look after the 'Feedback' aspect.

**Comment by hirparikh** [comment]
Simplicity and Eliminate the waste

**Comment by varsha-kankariya** [comment]
All team members selected XP values.
